#ifndef ES_LOCALIZATION_H
#define ES_LOCALIZATION_H

enum class LocalStrings {
    QUESTIONNAIRE_CONTINUE,
    SETTINGS_SET_DATE,
    SETTINGS_SET_TIME,
    SETTINGS_DOWNLOAD_DATA,
    SETTINGS_BACK,
    QUESTIONNAIRE_COMPLETED,
    NOTIFICATION,
    NOTIFICATION_START,
    DOWNLOAD_DATA_LOG,
    DOWNLOAD_SIGNAL_LOG
};


char* get_localized_string(LocalStrings loc_str);

#endif // ES_LOCALIZATION_H